AWSTemplateFormatVersion: '2010-09-09'
Description: "Manages Instance Profiles (Roles) for Common ECS Usage"

Resources:
  ecsInstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
      # RoleName: !Join [ "-", [ !Ref "AWS::Region", "ecsInstanceRole" ] ]

  ecsServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ecs.amazonaws.com"
                - "ec2.amazonaws.com"
                - "ecs-tasks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole
      # RoleName: !Join [ "-", [ !Ref "AWS::Region", "ecsServiceRole" ] ]

  ecsInstanceInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !Ref ecsInstanceRole

  ecsServiceInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !Ref ecsServiceRole

Outputs:
  ecsInstanceInstanceProfile:
    Description: Role which allows EC2 instances in an ECS cluster to access ECS.
    Value: !Ref ecsInstanceInstanceProfile
    Export:
      Name: ecsInstanceRole
  ecsServiceInstanceProfile:
    Description: Role which allows ECS to make adjustments to infra as needed.
    Value: !Ref ecsServiceInstanceProfile
    Export:
      Name: ecsServiceRole
